### PR TITLE
Синхронизация видео 

### PR DESCRIPTION
**Pull request by ArtemGolovanov**
[Review on Reviewable](https://reviewable.io/reviews/basepractice/2015.2/79)

### CODE REVIEW

**Comment by Pastor** [comment]
Добавьте модуль в главный `pom.xml`,  сборка не проходит

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[Examples/coursej/src/main/java/ru/mirea/oop/practice/coursej/api/vk/entities/Video.java, line 26 \[r1\]](https://reviewable.io:443/reviews/basepractice/2015.2/79#-K6Z6f6wsYmmlWkMBsfR:-K6Z6f6wsYmmlWkMBsfS:-549644694) ([raw file](https://github.com/basepractice/2015.2/blob/3c630a25fd7563efc21d0e213db2afa093585f12/Examples/coursej/src/main/java/ru/mirea/oop/practice/coursej/api/vk/entities/Video.java#L26)):*
У полей не может быть таких имен, читайте конвенцию

---

*[Examples/s131231/src/main/java/ru/mirea/oop/practice/coursej/s131231/VkVideoSync.java, line 33 \[r1\]](https://reviewable.io:443/reviews/basepractice/2015.2/79#-K6Z75bZps_oVFV_LylS:-K6Z75bZps_oVFV_LylT:2084102194) ([raw file](https://github.com/basepractice/2015.2/blob/3c630a25fd7563efc21d0e213db2afa093585f12/Examples/s131231/src/main/java/ru/mirea/oop/practice/coursej/s131231/VkVideoSync.java#L33)):*
Есть `File.separator`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/basepractice/2015.2/79#-:-K6Z7WpXyGzlAYd2Psmh:-23693663)*

**Comment by ArtemGolovanov** [comment]
Поправил 

---

Review status: 9 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[Examples/coursej/src/main/java/ru/mirea/oop/practice/coursej/api/vk/entities/Video.java, line 26 \[r1\]](https://reviewable.io:443/reviews/basepractice/2015.2/79#-K6Z6f6wsYmmlWkMBsfR:-K6ZD7CihwqMDOBgUfJW:-499146009) ([raw file](https://github.com/basepractice/2015.2/blob/3c630a25fd7563efc21d0e213db2afa093585f12/Examples/coursej/src/main/java/ru/mirea/oop/practice/coursej/api/vk/entities/Video.java#L26)):*
Done.

---

*[Examples/s131231/src/main/java/ru/mirea/oop/practice/coursej/s131231/VkVideoSync.java, line 33 \[r1\]](https://reviewable.io:443/reviews/basepractice/2015.2/79#-K6Z75bZps_oVFV_LylS:-K6ZCzyjZFvg9mslXUpG:-499146009) ([raw file](https://github.com/basepractice/2015.2/blob/3c630a25fd7563efc21d0e213db2afa093585f12/Examples/s131231/src/main/java/ru/mirea/oop/practice/coursej/s131231/VkVideoSync.java#L33)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/basepractice/2015.2/79#-:-K6ZDBx2gqFX7eszl4c6:-1709061962)*

**Comment by Pastor** [comment]
Reviewed 1 of 3 files at r2.
Review status: 10 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[Examples/coursej/src/main/java/ru/mirea/oop/practice/coursej/api/vk/entities/Video.java, line 26 \[r1\]](https://reviewable.io:443/reviews/basepractice/2015.2/79#-K6Z6f6wsYmmlWkMBsfR:-K6ZE_euYLxFsnrUxbqG:-135814218) ([raw file](https://github.com/basepractice/2015.2/blob/3c630a25fd7563efc21d0e213db2afa093585f12/Examples/coursej/src/main/java/ru/mirea/oop/practice/coursej/api/vk/entities/Video.java#L26)):*
Не вижу. Как были `mp4_360` и т.д. - так и остались

---

*[Examples/s131231/src/main/java/ru/mirea/oop/practice/coursej/s131231/VkVideoSync.java, line 33 \[r1\]](https://reviewable.io:443/reviews/basepractice/2015.2/79#-K6Z75bZps_oVFV_LylS:-K6ZEoXiF454YtEAO47k:-394307117) ([raw file](https://github.com/basepractice/2015.2/blob/3c630a25fd7563efc21d0e213db2afa093585f12/Examples/s131231/src/main/java/ru/mirea/oop/practice/coursej/s131231/VkVideoSync.java#L33)):*
Done? Не вижу

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/basepractice/2015.2/79)*

**Comment by Pastor** [comment]
Не вижу, чтобы что-нибудь было исправлено

---

Review status: 10 of 12 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/basepractice/2015.2/79#-:-K6ZEuBEloOp9zX1jNzr:-248842714)*

**Comment by Pastor** [comment]
Reviewed 2 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/basepractice/2015.2/79)*

**Comment by Pastor** [comment]
Оформляйтесь

**Pull request merged**
