### PR TITLE
Добавление модуля курсовой по ключевым словам для вк.

### PR DESCRIPTION
**Pull request by PolinaSahanova**
[Review on Reviewable](https://reviewable.io/reviews/basepractice/2015.2/58)

### CODE REVIEW

**Comment by Pastor** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[Examples/s131072/pom.xml, line 132 \[r1\]](https://reviewable.io:443/reviews/basepractice/2015.2/58#-K5qSSAwrIv0pFnmQJ5X:-K5qSSAwrIv0pFnmQJ5Y:-1341522426) ([raw file](https://github.com/basepractice/2015.2/blob/eb308d66d8f1d7f052477079684bd27b0085ff60/Examples/s131072/pom.xml#L132)):*
Еще раз подключаете модуль, а зачем?

---

*[Examples/s131072/src/main/java/ru/mirea/oop/practice/coursej/s131072/Keywords.java, line 11 \[r1\]](https://reviewable.io:443/reviews/basepractice/2015.2/58#-K5qSQhGfeXynRnpW6Yv:-K5qSQhGfeXynRnpW6Yw:-2064271825) ([raw file](https://github.com/basepractice/2015.2/blob/eb308d66d8f1d7f052477079684bd27b0085ff60/Examples/s131072/src/main/java/ru/mirea/oop/practice/coursej/s131072/Keywords.java#L11)):*
Вас зовут `Paul`?

---

*[Examples/s131072/src/main/java/ru/mirea/oop/practice/coursej/s131072/Keywords.java, line 34 \[r1\]](https://reviewable.io:443/reviews/basepractice/2015.2/58#-K5qSGnDaw6d1SMk8Ovk:-K5qSGnDaw6d1SMk8Ovl:228129997) ([raw file](https://github.com/basepractice/2015.2/blob/eb308d66d8f1d7f052477079684bd27b0085ff60/Examples/s131072/src/main/java/ru/mirea/oop/practice/coursej/s131072/Keywords.java#L34)):*
Перенос строки. Вы сами писали?

---

*[Examples/s131072/src/main/java/ru/mirea/oop/practice/coursej/s131072/Parser.java, line 4 \[r1\]](https://reviewable.io:443/reviews/basepractice/2015.2/58#-K5qRHfsug7qL5EusxY5:-K5qRHfsug7qL5EusxY6:-2064271825) ([raw file](https://github.com/basepractice/2015.2/blob/eb308d66d8f1d7f052477079684bd27b0085ff60/Examples/s131072/src/main/java/ru/mirea/oop/practice/coursej/s131072/Parser.java#L4)):*
Вас зовут `Paul`?

---

*[Examples/s131072/src/main/java/ru/mirea/oop/practice/coursej/s131072/Parser.java, line 10 \[r1\]](https://reviewable.io:443/reviews/basepractice/2015.2/58#-K5qROl1j5fJYcX4DZ7b:-K5qROl1j5fJYcX4DZ7c:-235212631) ([raw file](https://github.com/basepractice/2015.2/blob/eb308d66d8f1d7f052477079684bd27b0085ff60/Examples/s131072/src/main/java/ru/mirea/oop/practice/coursej/s131072/Parser.java#L10)):*
Не обязательно передавать в конструктор пустую строку

---

*[Examples/s131072/src/main/java/ru/mirea/oop/practice/coursej/s131072/VkKeyWords.java, line 8 \[r1\]](https://reviewable.io:443/reviews/basepractice/2015.2/58#-K5qR_C1XWnyLhHw5lxl:-K5qR_C1XWnyLhHw5lxm:-1418081361) ([raw file](https://github.com/basepractice/2015.2/blob/eb308d66d8f1d7f052477079684bd27b0085ff60/Examples/s131072/src/main/java/ru/mirea/oop/practice/coursej/s131072/VkKeyWords.java#L8)):*
Поехало форматирование

---

*[Examples/s131072/src/main/java/ru/mirea/oop/practice/coursej/s131072/VkKeyWords.java, line 12 \[r1\]](https://reviewable.io:443/reviews/basepractice/2015.2/58#-K5qRbrBmDvw0HW7-Fu4:-K5qRbrBmDvw0HW7-Fu5:1175196579) ([raw file](https://github.com/basepractice/2015.2/blob/eb308d66d8f1d7f052477079684bd27b0085ff60/Examples/s131072/src/main/java/ru/mirea/oop/practice/coursej/s131072/VkKeyWords.java#L12)):*
Теперь я точно убедился, что вас все таки зовут `Paul` :smile: 

---

*[Examples/s131072/src/main/java/ru/mirea/oop/practice/coursej/s131072/VkKeyWords.java, line 39 \[r1\]](https://reviewable.io:443/reviews/basepractice/2015.2/58#-K5qRt15_hktX7wVUtvs:-K5qRt15_hktX7wVUtvt:-253397188) ([raw file](https://github.com/basepractice/2015.2/blob/eb308d66d8f1d7f052477079684bd27b0085ff60/Examples/s131072/src/main/java/ru/mirea/oop/practice/coursej/s131072/VkKeyWords.java#L39)):*
Используйте `{}`

---

*[Examples/s131072/src/main/java/ru/mirea/oop/practice/coursej/s131072/VkKeyWords.java, line 42 \[r1\]](https://reviewable.io:443/reviews/basepractice/2015.2/58#-K5qRxu0weu8YJX6MPlx:-K5qRxu0weu8YJX6MPly:-253397188) ([raw file](https://github.com/basepractice/2015.2/blob/eb308d66d8f1d7f052477079684bd27b0085ff60/Examples/s131072/src/main/java/ru/mirea/oop/practice/coursej/s131072/VkKeyWords.java#L42)):*
Используйте `{}`

---

*[Examples/s131072/src/main/java/ru/mirea/oop/practice/coursej/s131072/VkKeyWords.java, line 58 \[r1\]](https://reviewable.io:443/reviews/basepractice/2015.2/58#-K5qS-RzjslkR-chzo6o:-K5qS-RzjslkR-chzo6p:-253397188) ([raw file](https://github.com/basepractice/2015.2/blob/eb308d66d8f1d7f052477079684bd27b0085ff60/Examples/s131072/src/main/java/ru/mirea/oop/practice/coursej/s131072/VkKeyWords.java#L58)):*
Используйте `{}`

---

*[Examples/s131072/src/main/java/ru/mirea/oop/practice/coursej/s131072/VkKeyWords.java, line 65 \[r1\]](https://reviewable.io:443/reviews/basepractice/2015.2/58#-K5qS1hSb5O4YDOMBeMT:-K5qS1hSb5O4YDOMBeMU:-253397188) ([raw file](https://github.com/basepractice/2015.2/blob/eb308d66d8f1d7f052477079684bd27b0085ff60/Examples/s131072/src/main/java/ru/mirea/oop/practice/coursej/s131072/VkKeyWords.java#L65)):*
Используйте `{}`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/basepractice/2015.2/58)*

**Comment by Pastor** [comment]
Вы там как, сдавать собираетесь?
Почитайте, прежде чем пулить https://github.com/BasePractice/2015.2#Правила-игры

**Comment by PolinaSahanova** [comment]
*[Examples/s131072/pom.xml, line 132 \[r1\]](https://reviewable.io:443/reviews/basepractice/2015.2/58#-K5qSSAwrIv0pFnmQJ5X:-K5ttd3I9rzDBoMTy7Zv:302780895) ([raw file](https://github.com/basepractice/2015.2/blob/eb308d66d8f1d7f052477079684bd27b0085ff60/Examples/s131072/pom.xml#L132)):*
Виновата, не обратила внимание.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/basepractice/2015.2/58)*

**Comment by PolinaSahanova** [comment]
*[Examples/s131072/src/main/java/ru/mirea/oop/practice/coursej/s131072/VkKeyWords.java, line 12 \[r1\]](https://reviewable.io:443/reviews/basepractice/2015.2/58#-K5qRbrBmDvw0HW7-Fu4:-K5rKU8PsQSSOBXiyb2L:1309463338) ([raw file](https://github.com/basepractice/2015.2/blob/eb308d66d8f1d7f052477079684bd27b0085ff60/Examples/s131072/src/main/java/ru/mirea/oop/practice/coursej/s131072/VkKeyWords.java#L12)):*
"Пол" - сокращение от "Полина" на манер английского имени "Paul", вот и всё :) .

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/basepractice/2015.2/58)*

**Comment by Pastor** [comment]
Оформляйтесь

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/basepractice/2015.2/58#-:-K5uQ2yZtf9GCMJJJ7KH:-426260396)*

**Pull request merged**
