### PR TITLE
Lebedev. Вывод информации по запросу(локальное хранилище данных)

### PR DESCRIPTION
**Pull request by lebedev123**
[Review on Reviewable](https://reviewable.io/reviews/basepractice/2015.2/83)

### CODE REVIEW

**Comment by Pastor** [comment]
service.properties - не трогаем, удаляйте его изменение из Пула. Каково ваше задание на курсовую?
Прочитайте правила игры и внесите изменения.
Обновите свой репозиторий и напишите как и куда вы записываете регистрационные данные Telegram 

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[Examples/s131332/src/main/java/ru/mirea/oop/practice/coursej/s131332/Qrequests.java, line 10 \[r1\]](https://reviewable.io:443/reviews/basepractice/2015.2/83#-K7WBjGRvdWi6qz7r5Oz:-K7WBjGRvdWi6qz7r5P-:762712116) ([raw file](https://github.com/basepractice/2015.2/blob/7e7059134a35e8fa01a475560302dc40354b7a96/Examples/s131332/src/main/java/ru/mirea/oop/practice/coursej/s131332/Qrequests.java#L10)):*
Что означает это название?

---

*[Examples/s131332/src/main/java/ru/mirea/oop/practice/coursej/s131332/Qrequests.java, line 14 \[r1\]](https://reviewable.io:443/reviews/basepractice/2015.2/83#-K7WBfpEJ9WxiJ8Icm2x:-K7WBfpFsMyJQYLWXgKR:-79871343) ([raw file](https://github.com/basepractice/2015.2/blob/7e7059134a35e8fa01a475560302dc40354b7a96/Examples/s131332/src/main/java/ru/mirea/oop/practice/coursej/s131332/Qrequests.java#L14)):*
Читаем правила игры

---

*[Examples/s131332/src/main/java/ru/mirea/oop/practice/coursej/s131332/TgData.java, line 15 \[r1\]](https://reviewable.io:443/reviews/basepractice/2015.2/83#-K7WBrXF3cK3F_FsZcnA:-K7WBrXF3cK3F_FsZcnB:-982214458) ([raw file](https://github.com/basepractice/2015.2/blob/7e7059134a35e8fa01a475560302dc40354b7a96/Examples/s131332/src/main/java/ru/mirea/oop/practice/coursej/s131332/TgData.java#L15)):*
Это зачем?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/basepractice/2015.2/83#-:-K7WC3Z9b57Ezzhl9Ncb:301787910)*

**Comment by lebedev123** [comment]
Пишу токен в NotePad и сохраняю как все файлы (имя назначаю как .access_tokens) и кидаю в C:/Users/*Я*

**Comment by Pastor** [comment]
Что вы туда пишите(пример строки без своих данных)?
Уберите `service.properties`

---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[Examples/s131332/src/main/java/ru/mirea/oop/practice/coursej/s131332/DataBase.java, line 26 \[r3\]](https://reviewable.io:443/reviews/basepractice/2015.2/83#-K7WlMFB7CSEKWdUMNaV:-K7WlMFB7CSEKWdUMNaW:-1101939944) ([raw file](https://github.com/basepractice/2015.2/blob/2ef485f55e54b2fce1ae918c21bc7ef83e9199fd/Examples/s131332/src/main/java/ru/mirea/oop/practice/coursej/s131332/DataBase.java#L26)):*
`error` и добавите `ex` в лог

---

*[Examples/s131332/src/main/java/ru/mirea/oop/practice/coursej/s131332/DataBase.java, line 28 \[r3\]](https://reviewable.io:443/reviews/basepractice/2015.2/83#-K7WlXEXzeKcMMDLlivB:-K7WlXEY4h00rqbVBFr0:-1101939944) ([raw file](https://github.com/basepractice/2015.2/blob/2ef485f55e54b2fce1ae918c21bc7ef83e9199fd/Examples/s131332/src/main/java/ru/mirea/oop/practice/coursej/s131332/DataBase.java#L28)):*
`error` и добавите `ex` в лог

---

*[Examples/s131332/src/main/java/ru/mirea/oop/practice/coursej/s131332/TgData.java, line 15 \[r3\]](https://reviewable.io:443/reviews/basepractice/2015.2/83#-K7WlddCgPvmYkOtte_4:-K7WlddCgPvmYkOtte_5:-1567250106) ([raw file](https://github.com/basepractice/2015.2/blob/2ef485f55e54b2fce1ae918c21bc7ef83e9199fd/Examples/s131332/src/main/java/ru/mirea/oop/practice/coursej/s131332/TgData.java#L15)):*
При чем тут писатели? У вас задание по писателям?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/basepractice/2015.2/83#-:-K7WlqHMu2X3jCaSQi0w:478800428)*

**Comment by Pastor** [comment]
Читайте правила игры и исправляйте

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/basepractice/2015.2/83#-:-K7fxqE2TF7BqJBsEvX1:-1081957128)*

**Comment by Pastor** [comment]
И нафиг удаляйте из пула изменения `service.properties`

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/basepractice/2015.2/83#-:-K7fxvPLyZg9cg-dvTYy:1045374428)*

**Comment by Pastor** [comment]
перечитывайте, исправляйте

---

Review status: 7 of 9 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/basepractice/2015.2/83#-:-K7g3oTBiMMcEAPLNPEQ:-1634109868)*

**Comment by Pastor** [comment]
перечитывайте, исправляйте. Удаляйте из пула `service.properties`

---

Reviewed 4 of 4 files at r6.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/basepractice/2015.2/83#-:-K7gKGYylspG5qr8GnPY:934761691)*

**Comment by Pastor** [comment]
не принимается

---

Reviewed 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/basepractice/2015.2/83#-:-K7gs_WnlT70owhKowk1:1153299870)*

**Comment by Pastor** [comment]
Смотрим внимательно и исправляем имена переменных в соответствии с требованиями конвенции

---

Reviewed 3 of 3 files at r8.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/basepractice/2015.2/83#-:-K8KR13KJYspiO-BEQZz:704926146)*

**Comment by Pastor** [comment]
Удалите `service.properties`

---

Reviewed 3 of 3 files at r9.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/basepractice/2015.2/83#-:-K92GeQPwqQn66XFOdzi:-1333497910)*

**Pull request closed without merging**
